### ISSUE TITLE
args.fine needed for ABLTagger/models/SosBR

### ISSUE THREAD

**Issue by KoichiYasuoka** [hinrikur/far-ABLTagger#1]
Thank you @hinrikur for Faroese ABLTagger, but neither `-type fine` nor `-type coarse` works well.

```sh
$ python tag.py -i input.txt -m SosBR -type fine

[snip]

tag.py: error: [Errno 2] No such file or directory: './models/SosBR/args.fine'
```

I could use `-type combined` but it didn't output fine tags.

```sh
$ python tag.py -i input.txt -m SosBR -type combined

[snip]

Morphological lexicon embeddings in place
Ofta	D
taka	V
trøll	D
góða	A
manna	S
børn	S
.	K

Done! 
```

**Comment by hinrikur** [comment]
Thanks for pointing this out!

> Thank you @hinrikur for Faroese ABLTagger, but neither `-type fine` nor `-type coarse` works well.

As is, the provided model (SosBR) only tags using the `coarse` and `combined` tagging types. As `combined` is the default, the `-type` flag can essentially be omitted on the command line for fine tags. This was maybe not clear in the documentation.

> I could use `-type combined` but it didn't output fine tags.

The tagged output shown on the command line (in your example) is actually the output of the coarse tagging step. It prints to the command line due to a leftover from a debugging step. I have removed it from the code. The final tagged output should only appear in a separate output file, suffixed with `.tagged` by default. Hopefully this helps.

**Comment by KoichiYasuoka** [comment]
Thank you for the information. I've made `git pull` on far-ABLTagger to try again:

```
$ python tag.py -i input.txt -m SosBR -type combined

[snip]

Done!
$ cat input.txt.tagged
Ofta	DN
taka	VNPP
trøll	SMSA
góða	APSFSA
manna	SMPG
børn	SNPA
.	KE
```

Oh, that's what I want. Thank you again @hinrikur , and I close this issue.
